Global:
  model: PP-OCRv5_mobile_det
  mode: check_dataset # check_dataset/train/evaluate/predict
  module: text_det
  dataset_dir: 
  device: 
  output: 

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  epochs_iters: 200
  batch_size: 16
  learning_rate: 0.001
  pretrain_weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-OCRv5_mobile_det_pretrained.pdparams
  resume_path: null
  log_interval: 50
  eval_interval: 1
  save_interval: 50


Evaluate:
  weight_path: "output/best_accuracy/best_accuracy.pdparams"
  log_interval: 1

Export:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/PP-OCRv5_mobile_det_pretrained.pdparams

Predict:
  batch_size: 1
  model_dir: "output/best_accuracy/inference"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_001.png"
  kernel_option:
    run_mode: paddle
