Global:
  model: korean_PP-OCRv3_mobile_rec
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir:
  device: 
  output: 

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  epochs_iters: 100
  batch_size: 256
  learning_rate: 0.001
  pretrain_weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/korean_PP-OCRv3_mobile_rec_pretrained.pdparams
  # resume_path: pho_train_result/pho_rec/train_gpu0123_ep30_bs256_lr1e-3/iter_epoch_30/iter_epoch_30.pdparams
  resume_path: null
  log_interval: 1
  eval_interval: 1
  save_interval: 5

Evaluate:
  weight_path: "output/best_accuracy/best_accuracy.pdparams"
  log_interval: 1

Export:
  weight_path: https://paddle-model-ecology.bj.bcebos.com/paddlex/official_pretrained_model/korean_PP-OCRv3_mobile_rec_pretrained.pdparams

Predict:
  batch_size: 1
  model_dir: "output/best_accuracy/inference"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_rec_003_korean.png"
  kernel_option:
    run_mode: paddle
